import type { Boat } from './types';

export const boats: Boat[] = [
	{
		id: 'amel-super-maramu',
		design_name: 'Amel Super Maramu',
		manufacturer: 'Amel',
		year_range_start: 1989,
		year_range_end: 1999,
		length_ft: 53,
		beam_ft: 14.8,
		displacement_lbs: 37500,
		ballast_lbs: 11000,
		ballast_ratio: 0.29,
		lwl_ft: 43,
		sail_area_sqft: 1140,
		sa_displacement_ratio: 15.2,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter_ketch',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
				cabins: 3,
		berths: 6,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 38.5,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 238,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: true,
		generator_standard: true,
		notes: 'Purpose-built bluewater cruiser. Center cockpit, ketch rig. Known for robust systems and excellent passage-making ability.'
	},
	{
		id: 'amel-super-maramu-2000',
		design_name: 'Amel Super Maramu 2000',
		manufacturer: 'Amel',
		year_range_start: 1999,
		year_range_end: 2007,
		length_ft: 53,
		beam_ft: 14.8,
		displacement_lbs: 38000,
		ballast_lbs: 11200,
		ballast_ratio: 0.29,
		lwl_ft: 43,
		sail_area_sqft: 1140,
		sa_displacement_ratio: 15.0,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter_ketch',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
				cabins: 3,
		berths: 6,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 39.0,
		capsize_screening_value: 1.71,
		displacement_length_ratio: 242,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: true,
		generator_standard: true,
		notes: 'Updated version with improved electrical systems and interior. Same proven hull as original Super Maramu.'
	},
	{
		id: 'amel-54',
		design_name: 'Amel 54',
		manufacturer: 'Amel',
		year_range_start: 2002,
		year_range_end: 2012,
		length_ft: 54,
		beam_ft: 15.4,
		displacement_lbs: 41000,
		ballast_lbs: 12300,
		ballast_ratio: 0.30,
		lwl_ft: 46,
		sail_area_sqft: 1250,
		sa_displacement_ratio: 15.4,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter_ketch',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
				cabins: 3,
		berths: 7,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 40.2,
		capsize_screening_value: 1.68,
		displacement_length_ratio: 240,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: true,
		generator_standard: true,
		notes: 'Flagship Amel. Modern systems, larger interior, same bluewater DNA.'
	},
	{
		id: 'amel-maramu',
		design_name: 'Amel Maramu',
		manufacturer: 'Amel',
		year_range_start: 1978,
		year_range_end: 1989,
		length_ft: 45.3,
		beam_ft: 13.1,
		displacement_lbs: 30865,
		ballast_lbs: 8818,
		ballast_ratio: 0.29,
		lwl_ft: 35.8,
		sail_area_sqft: 900,
		sa_displacement_ratio: 14.5,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter_ketch',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
		cabins: 2,
		berths: 7,
		sea_berths: 4,
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 36.6,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 265,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Henri Amel design. 288 hulls built. The original Amel bluewater cruiser — predecessor to the Super Maramu. Proven circumnavigator.'
	},
	{
		id: 'valiant-40',
		design_name: 'Valiant 40',
		manufacturer: 'Valiant',
		year_range_start: 1973,
		year_range_end: 1990,
		length_ft: 39.8,
		beam_ft: 12.1,
		displacement_lbs: 22000,
		ballast_lbs: 8800,
		ballast_ratio: 0.40,
		lwl_ft: 33.5,
		sail_area_sqft: 750,
		sa_displacement_ratio: 15.9,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'canoe',
				cabins: 2,
		berths: 5,
		sea_berths: 3,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 32.8,
		capsize_screening_value: 1.82,
		displacement_length_ratio: 288,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Bob Perry design. One of the most respected bluewater cruisers ever built. Canoe stern, high ballast ratio.'
	},
	{
		id: 'valiant-42',
		design_name: 'Valiant 42',
		manufacturer: 'Valiant',
		year_range_start: 1990,
		year_range_end: 2007,
		length_ft: 42.2,
		beam_ft: 12.6,
		displacement_lbs: 24500,
		ballast_lbs: 10000,
		ballast_ratio: 0.41,
		lwl_ft: 35.5,
		sail_area_sqft: 820,
		sa_displacement_ratio: 16.0,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'canoe',
		cabins: 2,
		berths: 6,
		sea_berths: 4,
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 33.5,
		capsize_screening_value: 1.80,
		displacement_length_ratio: 275,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Evolution of the V-40. Aft cockpit (CE = center-entry interior layout). Excellent passage maker.'
	},
	{
		id: 'psc-37',
		design_name: 'Pacific Seacraft 37',
		manufacturer: 'Pacific Seacraft',
		year_range_start: 1977,
		year_range_end: 2003,
		length_ft: 37.2,
		beam_ft: 10.9,
		displacement_lbs: 16000,
		ballast_lbs: 6200,
		ballast_ratio: 0.39,
		lwl_ft: 27.8,
		sail_area_sqft: 650,
		sa_displacement_ratio: 15.6,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		galley_layout: 'u_shaped',
		stern_type: 'canoe',
		cabins: 2,
		berths: 5,
		sea_berths: 3,
		forefoot_depth: 'deep',
		motion_comfort_ratio: 35.0,
		capsize_screening_value: 1.75,
		displacement_length_ratio: 340,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'W.I.B. Crealock design. Gold standard for bluewater cruising in this size range. Fin keel with skeg-hung rudder, bulletproof construction.'
	},
	{
		id: 'psc-40',
		design_name: 'Pacific Seacraft 40',
		manufacturer: 'Pacific Seacraft',
		year_range_start: 1981,
		year_range_end: 2002,
		length_ft: 40.0,
		beam_ft: 11.8,
		displacement_lbs: 24000,
		ballast_lbs: 8600,
		ballast_ratio: 0.36,
		lwl_ft: 31.3,
		sail_area_sqft: 740,
		sa_displacement_ratio: 15.3,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		galley_layout: 'u_shaped',
		stern_type: 'canoe',
		cabins: 2,
		berths: 5,
		sea_berths: 3,
		forefoot_depth: 'deep',
		motion_comfort_ratio: 36.5,
		capsize_screening_value: 1.73,
		displacement_length_ratio: 330,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Crealock design. Bigger sister to the PSC 37 with more interior volume. Canoe stern, outstanding build quality.'
	},
	{
		id: 'ip-380',
		design_name: 'Island Packet 380',
		manufacturer: 'Island Packet',
		year_range_start: 1999,
		year_range_end: 2007,
		length_ft: 38.3,
		beam_ft: 12.5,
		displacement_lbs: 21000,
		ballast_lbs: 8200,
		ballast_ratio: 0.39,
		lwl_ft: 33.2,
		sail_area_sqft: 700,
		sa_displacement_ratio: 14.8,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
				cabins: 2,
		berths: 5,
		sea_berths: 3,
forefoot_depth: 'deep',
		motion_comfort_ratio: 33.0,
		capsize_screening_value: 1.86,
		displacement_length_ratio: 280,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Full keel, high freeboard. Excellent liveaboard and coastal cruiser. Can handle offshore but not a speedster.'
	},
	{
		id: 'ip-420',
		design_name: 'Island Packet 420',
		manufacturer: 'Island Packet',
		year_range_start: 2001,
		year_range_end: 2010,
		length_ft: 42.0,
		beam_ft: 13.5,
		displacement_lbs: 30000,
		ballast_lbs: 12000,
		ballast_ratio: 0.40,
		lwl_ft: 37.3,
		sail_area_sqft: 1088,
		sa_displacement_ratio: 16.2,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
		cabins: 2,
		berths: 6,
		sea_berths: 3,
		forefoot_depth: 'deep',
		motion_comfort_ratio: 35.2,
		capsize_screening_value: 1.81,
		displacement_length_ratio: 275,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Island Packet\'s sweet spot. Good blend of liveaboard space and offshore capability.'
	},
	{
		id: 'hc-33',
		design_name: 'Hans Christian 33',
		manufacturer: 'Hans Christian',
		year_range_start: 1978,
		year_range_end: 1992,
		length_ft: 33.0,
		beam_ft: 10.5,
		displacement_lbs: 16500,
		ballast_lbs: 6600,
		ballast_ratio: 0.40,
		lwl_ft: 26.3,
		sail_area_sqft: 540,
		sa_displacement_ratio: 14.5,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'canoe',
				cabins: 1,
		berths: 4,
		sea_berths: 2,
forefoot_depth: 'deep',
		motion_comfort_ratio: 34.0,
		capsize_screening_value: 1.79,
		displacement_length_ratio: 370,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Traditional double-ender. Heavy, slow, but extremely seaworthy. Beautiful teak interiors.'
	},
	{
		id: 'hc-38',
		design_name: 'Hans Christian 38',
		manufacturer: 'Hans Christian',
		year_range_start: 1980,
		year_range_end: 1994,
		length_ft: 38.0,
		beam_ft: 11.5,
		displacement_lbs: 26500,
		ballast_lbs: 9800,
		ballast_ratio: 0.37,
		lwl_ft: 30.5,
		sail_area_sqft: 791,
		sa_displacement_ratio: 14.8,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'canoe',
		cabins: 2,
		berths: 5,
		sea_berths: 3,
		forefoot_depth: 'deep',
		motion_comfort_ratio: 37.0,
		capsize_screening_value: 1.69,
		displacement_length_ratio: 350,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Larger HC with center cockpit option. Traditional construction, proven offshore.'
	},
	{
		id: 'cabo-rico-38',
		design_name: 'Cabo Rico 38',
		manufacturer: 'Cabo Rico',
		year_range_start: 1986,
		year_range_end: 2004,
		length_ft: 38.0,
		beam_ft: 11.5,
		displacement_lbs: 20000,
		ballast_lbs: 8000,
		ballast_ratio: 0.40,
		lwl_ft: 30.5,
		sail_area_sqft: 690,
		sa_displacement_ratio: 15.5,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'canoe',
		cabins: 2,
		berths: 5,
		sea_berths: 3,
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 34.5,
		capsize_screening_value: 1.77,
		displacement_length_ratio: 310,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'W.I.B. Crealock design. Full keel with keel-hung rudder. Beautiful lines, excellent build quality.'
	},
	{
		id: 'hallberg-rassy-42',
		design_name: 'Hallberg-Rassy 42',
		manufacturer: 'Hallberg-Rassy',
		year_range_start: 1992,
		year_range_end: 2003,
		length_ft: 42.0,
		beam_ft: 13.0,
		displacement_lbs: 24700,
		ballast_lbs: 9400,
		ballast_ratio: 0.38,
		lwl_ft: 35.0,
		sail_area_sqft: 850,
		sa_displacement_ratio: 16.2,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'sugar_scoop',
				cabins: 2,
		berths: 6,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 34.0,
		capsize_screening_value: 1.78,
		displacement_length_ratio: 268,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Swedish quality. Center cockpit, windshield. Great combination of comfort and offshore capability.'
	},
	{
		id: 'hallberg-rassy-46',
		design_name: 'Hallberg-Rassy 46',
		manufacturer: 'Hallberg-Rassy',
		year_range_start: 1996,
		year_range_end: 2006,
		length_ft: 46.0,
		beam_ft: 13.5,
		displacement_lbs: 36376,
		ballast_lbs: 14550,
		ballast_ratio: 0.40,
		lwl_ft: 38.5,
		sail_area_sqft: 1076,
		sa_displacement_ratio: 16.3,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'sugar_scoop',
				cabins: 3,
		berths: 7,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.8,
		capsize_screening_value: 1.74,
		displacement_length_ratio: 260,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Larger HR with more liveaboard space. Same build quality and offshore pedigree.'
	},
	{
		id: 'oyster-46-hp',
		design_name: 'Oyster 46 (Holman & Pye)',
		manufacturer: 'Oyster',
		year_range_start: 1982,
		year_range_end: 1990,
		length_ft: 46.0,
		beam_ft: 14.0,
		displacement_lbs: 31980,
		ballast_lbs: 12897,
		ballast_ratio: 0.40,
		lwl_ft: 39.6,
		sail_area_sqft: 980,
		sa_displacement_ratio: 15.4,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'ketch',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'sugar_scoop',
		cabins: 3,
		berths: 7,
		sea_berths: 4,
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 36.0,
		capsize_screening_value: 1.73,
		displacement_length_ratio: 255,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Holman & Pye staysail ketch. 25 hulls built. Classic British bluewater cruiser, ARC rally proven.'
	},
	{
		id: 'oyster-46-humphreys',
		design_name: 'Oyster 46 (Humphreys)',
		manufacturer: 'Oyster',
		year_range_start: 2005,
		year_range_end: 2012,
		length_ft: 46.8,
		beam_ft: 14.5,
		displacement_lbs: 35270,
		ballast_lbs: 11460,
		ballast_ratio: 0.32,
		lwl_ft: 40.6,
		sail_area_sqft: 1293,
		sa_displacement_ratio: 18.5,
		rudder_type: 'skeg_hung',
		keel_type: 'fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'center',
		hull_type: 'fin_keel',
		galley_layout: 'l_shaped',
		stern_type: 'sugar_scoop',
		cabins: 3,
		berths: 7,
		sea_berths: 4,
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.0,
		capsize_screening_value: 1.78,
		displacement_length_ratio: 250,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: true,
		generator_standard: true,
		notes: 'Rob Humphreys design. 29 hulls built 2005-2012, evolved into the 475. Modern luxury bluewater sloop.'
	},
	{
		id: 'swan-44',
		design_name: 'Swan 44',
		manufacturer: 'Nautor Swan',
		year_range_start: 1986,
		year_range_end: 1998,
		length_ft: 44.0,
		beam_ft: 13.2,
		displacement_lbs: 24300,
		ballast_lbs: 8400,
		ballast_ratio: 0.35,
		lwl_ft: 35.0,
		sail_area_sqft: 900,
		sa_displacement_ratio: 16.8,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'l_shaped',
		stern_type: 'transom',
				cabins: 2,
		berths: 6,
		sea_berths: 3,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 30.5,
		capsize_screening_value: 1.82,
		displacement_length_ratio: 248,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Performance-oriented bluewater yacht. German Frers design. Fast but capable offshore.'
	},
	{
		id: 'tayana-37',
		design_name: 'Tayana 37',
		manufacturer: 'Tayana',
		year_range_start: 1978,
		year_range_end: 1996,
		length_ft: 37.0,
		beam_ft: 11.3,
		displacement_lbs: 22500,
		ballast_lbs: 8000,
		ballast_ratio: 0.36,
		lwl_ft: 31.0,
		sail_area_sqft: 861,
		sa_displacement_ratio: 14.9,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'canoe',
				cabins: 2,
		berths: 5,
		sea_berths: 3,
forefoot_depth: 'deep',
		motion_comfort_ratio: 35.0,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 335,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Robert Perry design. Hugely popular bluewater cruiser. Double-ender, heavily built. Great value.'
	},
	{
		id: 'tayana-42',
		design_name: 'Tayana 42',
		manufacturer: 'Tayana',
		year_range_start: 1985,
		year_range_end: 1998,
		length_ft: 42.0,
		beam_ft: 12.8,
		displacement_lbs: 29157,
		ballast_lbs: 11800,
		ballast_ratio: 0.40,
		lwl_ft: 33.0,
		sail_area_sqft: 790,
		sa_displacement_ratio: 15.1,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'transom',
				cabins: 2,
		berths: 6,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.5,
		capsize_screening_value: 1.76,
		displacement_length_ratio: 285,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Center cockpit bluewater cruiser. Excellent value for size and capability.'
	},
	{
		id: 'hr-37',
		design_name: 'Hallberg-Rassy 37',
		manufacturer: 'Hallberg-Rassy',
		year_range_start: 2003,
		year_range_end: 2012,
		length_ft: 37.0,
		beam_ft: 11.7,
		displacement_lbs: 16535,
		ballast_lbs: 7055,
		ballast_ratio: 0.43,
		lwl_ft: 31.0,
		sail_area_sqft: 680,
		sa_displacement_ratio: 16.0,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'sugar_scoop',
				cabins: 2,
		berths: 5,
		sea_berths: 3,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 31.5,
		capsize_screening_value: 1.85,
		displacement_length_ratio: 265,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Compact HR with excellent fit and finish. Capable offshore cruiser in a manageable size.'
	},
	{
		id: 'ip-440',
		design_name: 'Island Packet 440',
		manufacturer: 'Island Packet',
		year_range_start: 2004,
		year_range_end: 2012,
		length_ft: 44.0,
		beam_ft: 13.8,
		displacement_lbs: 32000,
		ballast_lbs: 12000,
		ballast_ratio: 0.38,
		lwl_ft: 37.5,
		sail_area_sqft: 1131,
		sa_displacement_ratio: 16.2,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		galley_layout: 'u_shaped',
		stern_type: 'transom',
		cabins: 2,
		berths: 6,
		sea_berths: 3,
		forefoot_depth: 'deep',
		motion_comfort_ratio: 37.5,
		capsize_screening_value: 1.75,
		displacement_length_ratio: 280,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Large Island Packet. Generous interior volume. Trades upwind performance for comfort and stability.'
	},
	{
		id: 'wauquiez-pilot-saloon-43',
		design_name: 'Wauquiez Pilot Saloon 43',
		manufacturer: 'Wauquiez',
		year_range_start: 1998,
		year_range_end: 2006,
		length_ft: 43.0,
		beam_ft: 13.6,
		displacement_lbs: 24000,
		ballast_lbs: 9200,
		ballast_ratio: 0.38,
		lwl_ft: 36.5,
		sail_area_sqft: 860,
		sa_displacement_ratio: 16.5,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		galley_layout: 'l_shaped',
		stern_type: 'transom',
				cabins: 2,
		berths: 6,
		sea_berths: 4,
forefoot_depth: 'moderate',
		motion_comfort_ratio: 32.0,
		capsize_screening_value: 1.84,
		displacement_length_ratio: 248,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Raised saloon design with excellent visibility. Deck saloon makes for great liveaboard. Capable offshore.'
	},
	{
		id: 'beneteau-oceanis-390',
		design_name: 'Beneteau Oceanis 390',
		manufacturer: 'Beneteau',
		year_range_start: 1988,
		year_range_end: 1995,
		length_ft: 37.2,
		beam_ft: 12.8,
		displacement_lbs: 14300,
		ballast_lbs: 5180,
		ballast_ratio: 0.36,
		lwl_ft: 33.5,
		sail_area_sqft: 630,
		sa_displacement_ratio: 18.2,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'corridor',
		stern_type: 'transom',
				cabins: 2,
		berths: 6,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 24.0,
		capsize_screening_value: 2.15,
		displacement_length_ratio: 185,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Production cruiser. Capable coastal cruiser but not ideal for extended offshore. Light displacement, fast in moderate conditions.'
	},
	{
		id: 'catalina-42',
		design_name: 'Catalina 42',
		manufacturer: 'Catalina',
		year_range_start: 1989,
		year_range_end: 2004,
		length_ft: 42.0,
		beam_ft: 13.75,
		displacement_lbs: 18500,
		ballast_lbs: 7200,
		ballast_ratio: 0.39,
		lwl_ft: 35.5,
		sail_area_sqft: 755,
		sa_displacement_ratio: 16.1,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'corridor',
		stern_type: 'transom',
				cabins: 2,
		berths: 6,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 28.0,
		capsize_screening_value: 2.05,
		displacement_length_ratio: 210,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Popular American production cruiser. Roomy, comfortable, good value. Excellent coastal cruiser and capable weekend racer.'
	},
	{
		id: 'catalina-36',
		design_name: 'Catalina 36',
		manufacturer: 'Catalina',
		year_range_start: 1983,
		year_range_end: 2001,
		length_ft: 36.3,
		beam_ft: 11.9,
		displacement_lbs: 15000,
		ballast_lbs: 5800,
		ballast_ratio: 0.39,
		lwl_ft: 30.2,
		sail_area_sqft: 555,
		sa_displacement_ratio: 14.8,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'corridor',
		stern_type: 'transom',
				cabins: 2,
		berths: 5,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 27.5,
		capsize_screening_value: 2.0,
		displacement_length_ratio: 235,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Best-selling cruising sailboat in North America. Easy to handle, comfortable, affordable. Great starter bluewater boat for couples.'
	},
	{
		id: 'jeanneau-sun-odyssey-42',
		design_name: 'Jeanneau Sun Odyssey 42',
		manufacturer: 'Jeanneau',
		year_range_start: 1998,
		year_range_end: 2007,
		length_ft: 42.0,
		beam_ft: 13.5,
		displacement_lbs: 18700,
		ballast_lbs: 5950,
		ballast_ratio: 0.32,
		lwl_ft: 36.0,
		sail_area_sqft: 830,
		sa_displacement_ratio: 17.5,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'corridor',
		stern_type: 'transom',
				cabins: 3,
		berths: 6,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 26.0,
		capsize_screening_value: 2.08,
		displacement_length_ratio: 200,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'French production cruiser. Fast, modern lines, comfortable interior. Popular charter and coastal cruising boat.'
	},
	{
		id: 'jeanneau-sun-odyssey-49',
		design_name: 'Jeanneau Sun Odyssey 49',
		manufacturer: 'Jeanneau',
		year_range_start: 2004,
		year_range_end: 2010,
		length_ft: 49.5,
		beam_ft: 15.0,
		displacement_lbs: 26900,
		ballast_lbs: 7700,
		ballast_ratio: 0.29,
		lwl_ft: 42.0,
		sail_area_sqft: 1050,
		sa_displacement_ratio: 17.0,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'open_linear',
		stern_type: 'sugar_scoop',
				cabins: 3,
		berths: 8,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 27.5,
		capsize_screening_value: 2.1,
		displacement_length_ratio: 180,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Large, spacious production cruiser. Excellent liveaboard potential. Wide beam provides generous interior volume.'
	},
	{
		id: 'beneteau-oceanis-46',
		design_name: 'Beneteau Oceanis 46',
		manufacturer: 'Beneteau',
		year_range_start: 2007,
		year_range_end: 2013,
		length_ft: 45.9,
		beam_ft: 14.5,
		displacement_lbs: 22700,
		ballast_lbs: 6200,
		ballast_ratio: 0.27,
		lwl_ft: 39.5,
		sail_area_sqft: 960,
		sa_displacement_ratio: 17.8,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'open_linear',
		stern_type: 'sugar_scoop',
				cabins: 3,
		berths: 8,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 25.5,
		capsize_screening_value: 2.12,
		displacement_length_ratio: 190,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Modern production cruiser. Spacious, comfortable, easy to sail. Popular charter boat with good liveaboard potential.'
	},
	{
		id: 'hunter-41',
		design_name: 'Hunter 41',
		manufacturer: 'Hunter',
		year_range_start: 2000,
		year_range_end: 2005,
		length_ft: 40.3,
		beam_ft: 13.25,
		displacement_lbs: 19400,
		ballast_lbs: 6500,
		ballast_ratio: 0.34,
		lwl_ft: 36.0,
		sail_area_sqft: 928,
		sa_displacement_ratio: 16.5,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'open_linear',
		stern_type: 'transom',
				cabins: 2,
		berths: 6,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 25.0,
		capsize_screening_value: 2.1,
		displacement_length_ratio: 195,
		has_backstay: false,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'American production cruiser. B&R rig (no backstay), spacious interior, easy handling. Great coastal cruiser for families.'
	},
	{
		id: 'bavaria-42',
		design_name: 'Bavaria 42',
		manufacturer: 'Bavaria',
		year_range_start: 2002,
		year_range_end: 2010,
		length_ft: 42.3,
		beam_ft: 13.5,
		displacement_lbs: 19400,
		ballast_lbs: 6400,
		ballast_ratio: 0.33,
		lwl_ft: 36.5,
		sail_area_sqft: 840,
		sa_displacement_ratio: 17.0,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		galley_layout: 'open_linear',
		stern_type: 'transom',
				cabins: 3,
		berths: 6,
		sea_berths: 2,
forefoot_depth: 'cut_away',
		motion_comfort_ratio: 26.5,
		capsize_screening_value: 2.05,
		displacement_length_ratio: 205,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'German production cruiser. Good build quality for the price. Popular European coastal cruiser and charter boat.'
	},
	{
		id: 'little-harbor-38',
		design_name: 'Little Harbor 38',
		manufacturer: 'Little Harbor',
		year_range_start: 1982,
		year_range_end: 1988,
		length_ft: 38,
		beam_ft: 11.83,
		displacement_lbs: 20600,
		ballast_lbs: 8400,
		ballast_ratio: 0.41,
		lwl_ft: 31,
		sail_area_sqft: 739,
		sa_displacement_ratio: 15.8,
		rudder_type: 'spade',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.81,
		capsize_screening_value: 1.73,
		displacement_length_ratio: 309,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Ted Hood design. 31 hulls built by Lien Hwa. Centerboard with lead ballast for shoal-draft versatility. Excellent build quality and seakeeping. Hood trademark adjustable draft — 4.5ft board up, 9.5ft board down.'
	},
	{
		id: 'little-harbor-44',
		design_name: 'Little Harbor 44',
		manufacturer: 'Little Harbor',
		year_range_start: 1983,
		year_range_end: 1987,
		length_ft: 44.33,
		beam_ft: 13.67,
		displacement_lbs: 32500,
		ballast_lbs: 13800,
		ballast_ratio: 0.42,
		lwl_ft: 36.5,
		sail_area_sqft: 937,
		sa_displacement_ratio: 14.78,
		rudder_type: 'spade',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 39.72,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 298,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Ted Hood design. 15 hulls built. High ballast ratio (42.5%) and centerboard for exceptional stability and shoal-draft access. Premium semi-custom build quality.'
	},
	{
		id: 'little-harbor-46',
		design_name: 'Little Harbor 46',
		manufacturer: 'Little Harbor',
		year_range_start: 1986,
		year_range_end: 1992,
		length_ft: 45.67,
		beam_ft: 13.75,
		displacement_lbs: 32500,
		ballast_lbs: 13800,
		ballast_ratio: 0.42,
		lwl_ft: 36.5,
		sail_area_sqft: 966,
		sa_displacement_ratio: 15.24,
		rudder_type: 'spade',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 39.01,
		capsize_screening_value: 1.73,
		displacement_length_ratio: 298,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Ted Hood design. 21 hulls built. Cutter rig for bluewater versatility. Same displacement and ballast as the 44 on a slightly longer hull. Centerboard — 5ft board up, 10ft board down.'
	},
	{
		id: 'little-harbor-50',
		design_name: 'Little Harbor 50',
		manufacturer: 'Little Harbor',
		year_range_start: 1982,
		length_ft: 50.75,
		beam_ft: 15.08,
		displacement_lbs: 43200,
		ballast_lbs: 18000,
		ballast_ratio: 0.42,
		lwl_ft: 42.17,
		sail_area_sqft: 1250,
		sa_displacement_ratio: 16.32,
		rudder_type: 'spade',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 40.23,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 257,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Ted Hood design. Semi-custom bluewater cruiser. Centerboard — 5.5ft board up, 11.5ft board down. 330 gallon water capacity. Proven offshore passagemaker with shoal-draft versatility.'
	},
	{
		id: 'little-harbor-54',
		design_name: 'Little Harbor 54',
		manufacturer: 'Little Harbor',
		year_range_start: 1989,
		length_ft: 54,
		beam_ft: 15,
		displacement_lbs: 62359,
		ballast_lbs: 19000,
		ballast_ratio: 0.30,
		lwl_ft: 43.17,
		sail_area_sqft: 1272,
		sa_displacement_ratio: 13.0,
		rudder_type: 'spade',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'center',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 56.38,
		capsize_screening_value: 1.52,
		displacement_length_ratio: 346,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: true,
		generator_standard: true,
		notes: 'Ted Hood design. Flagship heavy-displacement bluewater cruiser. Exceptional motion comfort ratio (56.4) and capsize screening (1.52). Centerboard — 6.3ft board up, 12.1ft board down. Center cockpit for serious offshore passages.'
	},
	{
		id: 'alden-44',
		design_name: 'Alden 44',
		manufacturer: 'Alden',
		year_range_start: 1976,
		year_range_end: 1991,
		length_ft: 44.16,
		beam_ft: 12.5,
		displacement_lbs: 24500,
		ballast_lbs: 10000,
		ballast_ratio: 0.41,
		lwl_ft: 34.08,
		sail_area_sqft: 871,
		sa_displacement_ratio: 16.59,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.31,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 276,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Alden Associates / Nils Helleberg design. 40 hulls built by Tillotson Pearson. Centerboard cutter — 4.9ft board up, 8.75ft board down. Originally designed as IOR racer, evolved into capable bluewater cruiser.'
	},
	{
		id: 'alden-44-mkii',
		design_name: 'Alden 44 MkII',
		manufacturer: 'Alden',
		year_range_start: 1981,
		length_ft: 44.16,
		beam_ft: 12.46,
		displacement_lbs: 24500,
		ballast_lbs: 10000,
		ballast_ratio: 0.41,
		lwl_ft: 34.92,
		sail_area_sqft: 871,
		sa_displacement_ratio: 16.59,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 34.91,
		capsize_screening_value: 1.72,
		displacement_length_ratio: 257,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Alden Associates design. Updated version of the Alden 44 with modified rudder/skeg, repositioned propeller shaft, and revised interior layout. Sloop rig replaces original cutter.'
	},
	{
		id: 'alden-46',
		design_name: 'Alden 46',
		manufacturer: 'Alden',
		year_range_start: 1987,
		year_range_end: 1997,
		length_ft: 47.67,
		beam_ft: 13.5,
		displacement_lbs: 32000,
		ballast_lbs: 13000,
		ballast_ratio: 0.41,
		lwl_ft: 37.08,
		sail_area_sqft: 1076,
		sa_displacement_ratio: 17.15,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 38.38,
		capsize_screening_value: 1.70,
		displacement_length_ratio: 280,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Niels Helleberg design. Centerboard — 5.3ft board up, 10.1ft board down. High ballast ratio (40.6%) with good SA/D (17.15) for a cruiser — well balanced between performance and comfort.'
	},
	{
		id: 'alden-50',
		design_name: 'Alden 50',
		manufacturer: 'Alden',
		year_range_start: 1996,
		year_range_end: 1998,
		length_ft: 50.33,
		beam_ft: 13.5,
		displacement_lbs: 38000,
		ballast_lbs: 16300,
		ballast_ratio: 0.43,
		lwl_ft: 37.08,
		sail_area_sqft: 1092,
		sa_displacement_ratio: 15.52,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 44.68,
		capsize_screening_value: 1.61,
		displacement_length_ratio: 333,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Alden Yachts design. Only 3 built — rare semi-custom bluewater cruiser. Highest ballast ratio (42.9%) in the Alden line. Centerboard — 5.5ft board up, 10.3ft board down. Excellent comfort ratio (44.7).'
	},
	{
		id: 'alden-54',
		design_name: 'Alden 54',
		manufacturer: 'Alden',
		year_range_start: 1985,
		year_range_end: 2002,
		length_ft: 54.08,
		beam_ft: 14.33,
		displacement_lbs: 36500,
		ballast_lbs: 15000,
		ballast_ratio: 0.41,
		lwl_ft: 40,
		sail_area_sqft: 1221,
		sa_displacement_ratio: 17.83,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 36.81,
		capsize_screening_value: 1.73,
		displacement_length_ratio: 255,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Alden design. Cutter rig with good SA/D (17.83) — fastest of the Alden line. Centerboard — 5.5ft board up, 10.5ft board down. Long production run (1985-2002) speaks to the design quality.'
	},
	{
		id: 'hylas-44',
		design_name: 'Hylas 44',
		manufacturer: 'Hylas',
		year_range_start: 1984,
		year_range_end: 1993,
		length_ft: 44.17,
		beam_ft: 13.5,
		displacement_lbs: 22320,
		ballast_lbs: 11020,
		ballast_ratio: 0.49,
		lwl_ft: 34.87,
		sail_area_sqft: 866,
		sa_displacement_ratio: 17.55,
		rudder_type: 'skeg_hung',
		keel_type: 'fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 28.61,
		capsize_screening_value: 1.92,
		displacement_length_ratio: 235,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'German Frers design. Built by Queen Long Marine (Taiwan). Exceptional ballast ratio (49.4%) — among the stiffest designs in class. Fast and capable offshore cruiser.'
	},
	{
		id: 'bristol-45-5',
		design_name: 'Bristol 45.5',
		manufacturer: 'Bristol',
		year_range_start: 1979,
		year_range_end: 1989,
		length_ft: 45.25,
		beam_ft: 13.16,
		displacement_lbs: 34660,
		ballast_lbs: 15000,
		ballast_ratio: 0.43,
		lwl_ft: 37.25,
		sail_area_sqft: 988,
		sa_displacement_ratio: 14.93,
		rudder_type: 'spade',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 43.66,
		capsize_screening_value: 1.62,
		displacement_length_ratio: 299,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Ted Hood design. Centerboard — 4.9ft board up, 11ft board down. Same design DNA as Little Harbor line. Excellent comfort ratio (43.7) and capsize screening (1.62). Balsa-cored deck.'
	},
	{
		id: 'shannon-43',
		design_name: 'Shannon 43',
		manufacturer: 'Shannon',
		year_range_start: 1986,
		length_ft: 43.83,
		beam_ft: 13,
		displacement_lbs: 27000,
		ballast_lbs: 10000,
		ballast_ratio: 0.37,
		lwl_ft: 36.58,
		sail_area_sqft: 910,
		sa_displacement_ratio: 16.24,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'ketch',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.37,
		capsize_screening_value: 1.74,
		displacement_length_ratio: 246,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Walter Schultz design. Staysail ketch with centerboard — 4.75ft board up, 8.6ft board down. Built in USA by Shannon Yachts. Serious bluewater cruiser.'
	},
	{
		id: 'shannon-38',
		design_name: 'Shannon 38',
		manufacturer: 'Shannon',
		year_range_start: 1975,
		year_range_end: 1988,
		length_ft: 37.75,
		beam_ft: 11.5,
		displacement_lbs: 18500,
		ballast_lbs: 6500,
		ballast_ratio: 0.35,
		lwl_ft: 30.83,
		sail_area_sqft: 703,
		sa_displacement_ratio: 16.14,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		stern_type: 'transom',
		forefoot_depth: 'deep',
		motion_comfort_ratio: 33.59,
		capsize_screening_value: 1.74,
		displacement_length_ratio: 282,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Stadel / Schultz design. 100 hulls built. Long keel cutter — classic bluewater layout. Built in USA by Shannon Yachts. Proven offshore passagemaker.'
	},
	{
		id: 'outbound-44-46',
		design_name: 'Outbound 44/46',
		manufacturer: 'Outbound',
		year_range_start: 2001,
		length_ft: 44.75,
		beam_ft: 13.5,
		displacement_lbs: 28000,
		ballast_lbs: 10000,
		ballast_ratio: 0.36,
		lwl_ft: 40.25,
		sail_area_sqft: 1083,
		sa_displacement_ratio: 18.87,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'transom',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 32.49,
		capsize_screening_value: 1.78,
		displacement_length_ratio: 192,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Carl Schumacher design. 50 built. Modern fast bluewater cruiser — highest SA/D (18.9) in the bluewater class. Long waterline (40.25ft on 44.75 LOA) for speed. 200 gallon fuel capacity.'
	},
	{
		id: 'westsail-32',
		design_name: 'Westsail 32',
		manufacturer: 'Westsail',
		year_range_start: 1971,
		year_range_end: 1981,
		length_ft: 32,
		beam_ft: 11,
		displacement_lbs: 19500,
		ballast_lbs: 7000,
		ballast_ratio: 0.36,
		lwl_ft: 27.5,
		sail_area_sqft: 753,
		sa_displacement_ratio: 16.69,
		rudder_type: 'transom_hung',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		stern_type: 'canoe',
		forefoot_depth: 'deep',
		motion_comfort_ratio: 42.85,
		capsize_screening_value: 1.64,
		displacement_length_ratio: 419,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Crealock / Atkin design. 834 hulls built — iconic small bluewater cruiser. Full keel, canoe stern, transom-hung rudder. Colin Archer influence. Heavy displacement (D/L 419) but proven circumnavigator.'
	},
	{
		id: 'mason-44',
		design_name: 'Mason 44',
		manufacturer: 'Mason',
		year_range_start: 1985,
		length_ft: 43.92,
		beam_ft: 12.25,
		displacement_lbs: 27400,
		ballast_lbs: 9400,
		ballast_ratio: 0.34,
		lwl_ft: 31.75,
		sail_area_sqft: 921,
		sa_displacement_ratio: 16.28,
		rudder_type: 'full_keel_integrated',
		keel_type: 'full',
		mast_step: 'keel_stepped',
		rig_type: 'ketch',
		cockpit_type: 'aft',
		hull_type: 'full_keel',
		stern_type: 'canoe',
		forefoot_depth: 'deep',
		motion_comfort_ratio: 42.52,
		capsize_screening_value: 1.63,
		displacement_length_ratio: 382,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Al Mason / Jeff Leishman design. Built by Ta Shing (Taiwan) — renowned build quality. Long keel, canoe stern, ketch rig. Classic heavy-displacement bluewater cruiser.'
	},
	{
		id: 'passport-40',
		design_name: 'Passport 40',
		manufacturer: 'Passport',
		year_range_start: 1980,
		year_range_end: 1991,
		length_ft: 39.42,
		beam_ft: 12.67,
		displacement_lbs: 22771,
		ballast_lbs: 8500,
		ballast_ratio: 0.37,
		lwl_ft: 33.42,
		sail_area_sqft: 762,
		sa_displacement_ratio: 15.24,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 33.96,
		capsize_screening_value: 1.79,
		displacement_length_ratio: 272,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Robert Perry design. 148 hulls built (Taiwan). Fin keel with skeg-hung rudder. Well-balanced coastal/offshore cruiser. Moderate displacement for comfortable motion.'
	},
	{
		id: 'passport-42',
		design_name: 'Passport 42',
		manufacturer: 'Passport',
		year_range_start: 1981,
		year_range_end: 1988,
		length_ft: 42,
		beam_ft: 12.83,
		displacement_lbs: 25500,
		ballast_lbs: 9000,
		ballast_ratio: 0.35,
		lwl_ft: 34.83,
		sail_area_sqft: 764,
		sa_displacement_ratio: 14.17,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 35.62,
		capsize_screening_value: 1.75,
		displacement_length_ratio: 269,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Stan Huntingford design. 50 hulls built (Taiwan). Cutter rig with skeg-hung rudder. Heavier and more bluewater-focused than the Perry-designed 40.'
	},
	{
		id: 'hinckley-bermuda-40',
		design_name: 'Hinckley Bermuda 40',
		manufacturer: 'Hinckley',
		year_range_start: 1971,
		length_ft: 40,
		beam_ft: 11.75,
		displacement_lbs: 20000,
		ballast_lbs: 6500,
		ballast_ratio: 0.33,
		lwl_ft: 28.83,
		sail_area_sqft: 681,
		sa_displacement_ratio: 14.84,
		rudder_type: 'skeg_hung',
		keel_type: 'centerboard',
		mast_step: 'keel_stepped',
		rig_type: 'yawl',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 36.09,
		capsize_screening_value: 1.73,
		displacement_length_ratio: 373,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'William Tripp Jr. design. Built by Hinckley (Maine). Yawl rig with centerboard — 4.3ft board up, 8.6ft board down. Premium build quality. Classic bluewater yacht.'
	},
	{
		id: 'tartan-3700',
		design_name: 'Tartan 3700',
		manufacturer: 'Tartan',
		year_range_start: 1999,
		length_ft: 37,
		beam_ft: 12.66,
		displacement_lbs: 15950,
		ballast_lbs: 6000,
		ballast_ratio: 0.38,
		lwl_ft: 32.5,
		sail_area_sqft: 728,
		sa_displacement_ratio: 18.44,
		rudder_type: 'spade',
		keel_type: 'fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'transom',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 24.78,
		capsize_screening_value: 2.02,
		displacement_length_ratio: 207,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Tim Jackett design. Modern performance cruiser. Also available as keel/CB (4-8ft draft) and shoal keel (5ft). Light displacement, fast in moderate conditions. Better suited for coastal than extended offshore.'
	},
	{
		id: 'tartan-42',
		design_name: 'Tartan 42',
		manufacturer: 'Tartan',
		year_range_start: 1980,
		year_range_end: 1984,
		length_ft: 42,
		beam_ft: 12.25,
		displacement_lbs: 22000,
		ballast_lbs: 9000,
		ballast_ratio: 0.41,
		lwl_ft: 32,
		sail_area_sqft: 758,
		sa_displacement_ratio: 15.51,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 34.53,
		capsize_screening_value: 1.75,
		displacement_length_ratio: 300,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Sparkman & Stephens design. 34 hulls built. Fin keel with skeg-hung rudder. High ballast ratio (40.9%). Capable coastal and offshore cruiser with racing heritage.'
	},
	{
		id: 'contest-42s',
		design_name: 'Contest 42S',
		manufacturer: 'Contest',
		year_range_start: 1998,
		year_range_end: 2002,
		length_ft: 41.17,
		beam_ft: 12.8,
		displacement_lbs: 29024,
		ballast_lbs: 11078,
		ballast_ratio: 0.38,
		lwl_ft: 34.45,
		sail_area_sqft: 962,
		sa_displacement_ratio: 16.37,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 41.24,
		capsize_screening_value: 1.67,
		displacement_length_ratio: 317,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Dick Zaal design. 9 built by Conyplex (Netherlands). Dutch quality bluewater cruiser. Excellent comfort ratio (41.2) and capsize screening (1.67).'
	},
	{
		id: 'contest-46',
		design_name: 'Contest 46',
		manufacturer: 'Contest',
		year_range_start: 1987,
		year_range_end: 1996,
		length_ft: 46.42,
		beam_ft: 13.75,
		displacement_lbs: 33960,
		ballast_lbs: 13668,
		ballast_ratio: 0.40,
		lwl_ft: 38.92,
		keel_type: 'wing',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 38.86,
		capsize_screening_value: 1.70,
		displacement_length_ratio: 257,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: true,
		notes: 'Dick Zaal design. 55 built by Conyplex (Netherlands). Wing keel for performance and shallow draft (6.4ft). High ballast ratio (40.3%). Proven bluewater cruiser.'
	},
	{
		id: 'bowman-40',
		design_name: 'Bowman 40',
		manufacturer: 'Bowman',
		year_range_start: 1987,
		length_ft: 39.92,
		beam_ft: 12.58,
		displacement_lbs: 19000,
		lwl_ft: 32,
		sail_area_sqft: 743,
		sa_displacement_ratio: 16.76,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 29.31,
		capsize_screening_value: 1.89,
		displacement_length_ratio: 259,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Chuck Paine design. 60 built by Southern Boat Building (UK). Shoal keel cutter (4.9ft draft). British-built bluewater cruiser.'
	},
	{
		id: 'bowman-42',
		design_name: 'Bowman 42',
		manufacturer: 'Bowman',
		year_range_start: 1998,
		length_ft: 43.08,
		beam_ft: 12.58,
		displacement_lbs: 21429,
		ballast_lbs: 6800,
		ballast_ratio: 0.32,
		lwl_ft: 32.75,
		sail_area_sqft: 894,
		sa_displacement_ratio: 18.61,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 31.70,
		capsize_screening_value: 1.82,
		displacement_length_ratio: 272,
		has_backstay: true,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Chuck Paine design. Built by Bowman / Rustler Yachts (UK). Cutter rig with skeg-hung rudder. Good SA/D (18.6) for a bluewater cutter. Shallow keel option at 5.9ft.'
	},
	{
		id: 'morris-46',
		design_name: 'Morris 46',
		manufacturer: 'Morris',
		year_range_start: 1994,
		year_range_end: 2007,
		length_ft: 45.92,
		beam_ft: 13,
		displacement_lbs: 23500,
		ballast_lbs: 8630,
		ballast_ratio: 0.37,
		lwl_ft: 34.5,
		sail_area_sqft: 879,
		sa_displacement_ratio: 17.21,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 31.45,
		capsize_screening_value: 1.82,
		displacement_length_ratio: 255,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Chuck Paine design. 14 built by Morris Yachts (Maine). Premium semi-custom build. Shallow draft (5.5ft) with good performance. Beautiful Maine craftsmanship.'
	},
	{
		id: 'morris-40',
		design_name: 'Morris 40',
		manufacturer: 'Morris',
		year_range_start: 1995,
		length_ft: 40.92,
		beam_ft: 12.58,
		displacement_lbs: 19400,
		lwl_ft: 32,
		sail_area_sqft: 757,
		sa_displacement_ratio: 16.84,
		rudder_type: 'skeg_hung',
		keel_type: 'modified_fin',
		mast_step: 'keel_stepped',
		rig_type: 'cutter',
		cockpit_type: 'aft',
		hull_type: 'modified_full',
		stern_type: 'transom',
		forefoot_depth: 'moderate',
		motion_comfort_ratio: 29.67,
		capsize_screening_value: 1.88,
		displacement_length_ratio: 264,
		has_backstay: true,
		has_teak_decks: true,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Chuck Paine design. Built by Morris Yachts (Maine). Cutter rig with shallow draft (5.25ft). Premium Maine craftsmanship. Same designer as Bowman 40/42.'
	},
	{
		id: 'beneteau-oceanis-45',
		design_name: 'Beneteau Oceanis 45',
		manufacturer: 'Beneteau',
		year_range_start: 2013,
		length_ft: 45.42,
		beam_ft: 14.75,
		displacement_lbs: 21048,
		lwl_ft: 42,
		sail_area_sqft: 1076,
		sa_displacement_ratio: 22.67,
		rudder_type: 'spade',
		keel_type: 'bulb_fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'sugar_scoop',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 20.99,
		capsize_screening_value: 2.14,
		displacement_length_ratio: 127,
		has_backstay: false,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Finot-Conq / Nauta Design. High-volume French production cruiser. Very light displacement (D/L 127), wide beam, fast but not comfortable offshore. Popular charter and coastal cruiser.'
	},
	{
		id: 'jeanneau-sun-odyssey-44i',
		design_name: 'Jeanneau Sun Odyssey 44i',
		manufacturer: 'Jeanneau',
		year_range_start: 2009,
		length_ft: 45.11,
		beam_ft: 14.34,
		displacement_lbs: 21892,
		ballast_lbs: 6512,
		ballast_ratio: 0.30,
		lwl_ft: 37.57,
		sail_area_sqft: 1082,
		sa_displacement_ratio: 22.21,
		rudder_type: 'spade',
		keel_type: 'bulb_fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'sugar_scoop',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 24.49,
		capsize_screening_value: 2.05,
		displacement_length_ratio: 184,
		has_backstay: false,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Philippe Briand design. French production cruiser. Light displacement with low ballast ratio (29.8%). Good coastal cruiser and charter boat. Wide beam for interior volume.'
	},
	{
		id: 'hanse-445',
		design_name: 'Hanse 445',
		manufacturer: 'Hanse',
		year_range_start: 2010,
		length_ft: 44.36,
		beam_ft: 14.37,
		displacement_lbs: 24251,
		ballast_lbs: 7716,
		ballast_ratio: 0.32,
		lwl_ft: 40.03,
		sail_area_sqft: 1021,
		sa_displacement_ratio: 19.58,
		rudder_type: 'spade',
		keel_type: 'bulb_fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'sugar_scoop',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 26.07,
		capsize_screening_value: 1.99,
		displacement_length_ratio: 169,
		has_backstay: false,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Judel/Vrolijk design. German production cruiser. Self-tacking jib option. Slightly heavier than French competitors. Good performer in moderate conditions.'
	},
	{
		id: 'dufour-460-grand-large',
		design_name: 'Dufour 460 Grand Large',
		manufacturer: 'Dufour',
		year_range_start: 2016,
		length_ft: 46.42,
		beam_ft: 14.76,
		displacement_lbs: 23721,
		ballast_lbs: 6283,
		ballast_ratio: 0.26,
		lwl_ft: 41.14,
		sail_area_sqft: 1073,
		sa_displacement_ratio: 20.88,
		rudder_type: 'spade',
		keel_type: 'bulb_fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'sugar_scoop',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 23.80,
		capsize_screening_value: 2.06,
		displacement_length_ratio: 152,
		has_backstay: false,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Umberto Felci design. French production cruiser. Lowest ballast ratio in the fleet (26.5%). Very light displacement. Fast and spacious but not for serious offshore work.'
	},
	{
		id: 'bavaria-cruiser-46',
		design_name: 'Bavaria Cruiser 46',
		manufacturer: 'Bavaria',
		year_range_start: 2014,
		length_ft: 46.82,
		beam_ft: 14.27,
		displacement_lbs: 27778,
		ballast_lbs: 7694,
		ballast_ratio: 0.28,
		lwl_ft: 42.45,
		sail_area_sqft: 1162,
		sa_displacement_ratio: 20.35,
		rudder_type: 'spade',
		keel_type: 'bulb_fin',
		mast_step: 'deck_stepped',
		rig_type: 'sloop',
		cockpit_type: 'aft',
		hull_type: 'fin_keel',
		stern_type: 'sugar_scoop',
		forefoot_depth: 'cut_away',
		motion_comfort_ratio: 28.47,
		capsize_screening_value: 1.89,
		displacement_length_ratio: 162,
		has_backstay: false,
		has_teak_decks: false,
		self_steering_compatible: true,
		watermaker_standard: false,
		generator_standard: false,
		notes: 'Farr Yacht Design. German production cruiser. Dual rudders, cast iron ballast. Heaviest of the modern production group but still light by bluewater standards. Popular charter boat.'
	}
];
